package com.baluhost.android.presentation.ui.components

import android.net.Uri
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.baluhost.android.domain.model.sync.ConflictResolution
import com.baluhost.android.domain.model.sync.SyncType

/**
 * Dialog to add a new sync folder configuration.
 * Simplifies the process by auto-generating remote path as "<localFolderName>/mobile"
 */
@Composable
fun AddSyncFolderDialog(
    localFolderUri: Uri?,
    localFolderName: String?,
    onDismiss: () -> Unit,
    onConfirm: (
        localPath: String,
        remotePath: String,
        syncType: SyncType,
        conflictResolution: ConflictResolution,
        autoSync: Boolean
    ) -> Unit
) {
    var syncType by remember { mutableStateOf(SyncType.UPLOAD_ONLY) }
    var conflictResolution by remember { mutableStateOf(ConflictResolution.KEEP_NEWEST) }
    var autoSync by remember { mutableStateOf(true) }
    var showSyncTypeDropdown by remember { mutableStateOf(false) }
    var showConflictResolutionDropdown by remember { mutableStateOf(false) }

    // Auto-generate remote path: folderName/mobile
    val autoGeneratedRemotePath = if (!localFolderName.isNullOrEmpty()) {
        "$localFolderName/mobile"
    } else {
        "sync/mobile"
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Icon(
                    imageVector = Icons.Default.Folder,
                    contentDescription = null,
                    modifier = Modifier.size(24.dp)
                )
                Text(
                    text = "Synchronisierter Ordner hinzufügen",
                    fontSize = 18.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 8.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Selected Local Folder
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = androidx.compose.material3.MaterialTheme.colorScheme.surfaceVariant
                    )
                ) {
                    Column(
                        modifier = Modifier.padding(12.dp),
                        verticalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Text(
                            text = "Lokales Verzeichnis",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.SemiBold,
                            color = androidx.compose.material3.MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Text(
                            text = localFolderName ?: "Kein Verzeichnis ausgewählt",
                            fontSize = 14.sp,
                            fontWeight = FontWeight.Bold
                        )
                    }
                }

                // Auto-generated Remote Path
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = androidx.compose.material3.MaterialTheme.colorScheme.primaryContainer
                    )
                ) {
                    Column(
                        modifier = Modifier.padding(12.dp),
                        verticalArrangement = Arrangement.spacedBy(4.dp)
                    ) {
                        Text(
                            text = "Automatisch generiert",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.SemiBold,
                            color = androidx.compose.material3.MaterialTheme.colorScheme.onPrimaryContainer
                        )
                        Text(
                            text = autoGeneratedRemotePath,
                            fontSize = 14.sp,
                            fontWeight = FontWeight.Bold,
                            color = androidx.compose.material3.MaterialTheme.colorScheme.onPrimaryContainer
                        )
                        Text(
                            text = "Der Pfad wird auf dem NAS automatisch erstellt",
                            fontSize = 11.sp,
                            color = androidx.compose.material3.MaterialTheme.colorScheme.onPrimaryContainer.copy(alpha = 0.7f)
                        )
                    }
                }

                Divider()

                // Sync Type Selection
                Text(
                    text = "Synchronisierungsrichtung",
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold
                )
                Box(modifier = Modifier.fillMaxWidth()) {
                    OutlinedButton(
                        onClick = { showSyncTypeDropdown = true },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(syncTypeLabel(syncType))
                            Icon(Icons.Default.ExpandMore, contentDescription = null)
                        }
                    }
                    DropdownMenu(
                        expanded = showSyncTypeDropdown,
                        onDismissRequest = { showSyncTypeDropdown = false }
                    ) {
                        SyncType.values().forEach { type ->
                            DropdownMenuItem(
                                text = { Text(syncTypeLabel(type)) },
                                onClick = {
                                    syncType = type
                                    showSyncTypeDropdown = false
                                }
                            )
                        }
                    }
                }

                // Conflict Resolution Strategy
                Text(
                    text = "Konfliktauflösung",
                    fontSize = 12.sp,
                    fontWeight = FontWeight.SemiBold
                )
                Box(modifier = Modifier.fillMaxWidth()) {
                    OutlinedButton(
                        onClick = { showConflictResolutionDropdown = true },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(conflictResolutionLabel(conflictResolution))
                            Icon(Icons.Default.ExpandMore, contentDescription = null)
                        }
                    }
                    DropdownMenu(
                        expanded = showConflictResolutionDropdown,
                        onDismissRequest = { showConflictResolutionDropdown = false }
                    ) {
                        ConflictResolution.values().forEach { strategy ->
                            DropdownMenuItem(
                                text = { Text(conflictResolutionLabel(strategy)) },
                                onClick = {
                                    conflictResolution = strategy
                                    showConflictResolutionDropdown = false
                                }
                            )
                        }
                    }
                }

                // Auto Sync Toggle
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 4.dp),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text(
                            text = "Automatische Synchronisierung",
                            fontSize = 13.sp,
                            fontWeight = FontWeight.SemiBold
                        )
                        Text(
                            text = "Synchronisiere automatisch im Hintergrund",
                            fontSize = 11.sp,
                            color = androidx.compose.material3.MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                    Switch(
                        checked = autoSync,
                        onCheckedChange = { autoSync = it }
                    )
                }
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    if (localFolderUri != null) {
                        onConfirm(
                            localFolderUri.toString(),
                            autoGeneratedRemotePath,
                            syncType,
                            conflictResolution,
                            autoSync
                        )
                    }
                },
                enabled = localFolderUri != null
            ) {
                Icon(
                    imageVector = Icons.Default.Check,
                    contentDescription = null,
                    modifier = Modifier.size(18.dp)
                )
                Spacer(modifier = Modifier.width(4.dp))
                Text("Hinzufügen")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Abbrechen")
            }
        }
    )
}

@Composable
private fun syncTypeLabel(type: SyncType): String = when (type) {
    SyncType.UPLOAD_ONLY -> "📱➡️ Nur hochladen"
    SyncType.DOWNLOAD_ONLY -> "⬅️📱 Nur herunterladen"
    SyncType.BIDIRECTIONAL -> "📱⬌🖥️ Bidirektional"
}

@Composable
private fun conflictResolutionLabel(strategy: ConflictResolution): String = when (strategy) {
    ConflictResolution.KEEP_LOCAL -> "Telefon bevorzugen"
    ConflictResolution.KEEP_SERVER -> "NAS bevorzugen"
    ConflictResolution.KEEP_NEWEST -> "Neueste Version (Standard)"
    ConflictResolution.ASK_USER -> "Mich fragen"
}
