#!/bin/bash
# Tests for install.sh module orchestration (issue #212).
#
# Runs the REAL install.sh + lib/ against stub modules in a temp sandbox, as
# an unprivileged user (require_root is overridden in the sandbox copy of
# common.sh — root behavior is not under test). Verifies:
#   1. A full non-interactive run executes ALL modules: a module's final
#      `exit 0` must not terminate the installer (issue #212).
#   2. Values a module persists via save_config (POSTGRES_PASSWORD from
#      stub 06) reach later modules (stub 07 asserts it).
#   3. A failing module stops the run with the resume hint and a nonzero
#      exit code; later modules do not run.
#   4. --module single mode propagates the module's exit code.
#   5. save_config/load_config round-trip values containing spaces, quotes
#      and dollar signs (ADMIN_PASSWORD is user-supplied).
#   6. A failing verify script does not suppress the completion banner.
#
# Usage: bash deploy/install/tests/test-install-orchestration.sh
set -uo pipefail

TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_SRC="$(cd "$TESTS_DIR/.." && pwd)"

PASS=0
FAIL=0
pass() { echo "PASS: $*"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $*" >&2; FAIL=$((FAIL + 1)); }

ALL_MODULES=(
    01-preflight 02-system-packages 03-user-setup 04-app-deploy
    05-python-venv 06-postgresql 07-env-generate 08-database-migrate
    09-frontend-build 10-systemd-services 11-nginx 12-start-services
    13-power-helpers 14-optional-features
)

make_sandbox() {
    SANDBOX=$(mktemp -d)
    cp "$INSTALL_SRC/install.sh" "$SANDBOX/"
    cp -r "$INSTALL_SRC/lib" "$SANDBOX/lib"
    mkdir -p "$SANDBOX/modules" "$SANDBOX/verify"

    # Tests run unprivileged; root is irrelevant to orchestration logic.
    echo 'require_root() { :; }' >> "$SANDBOX/lib/common.sh"

    local mod
    for mod in "${ALL_MODULES[@]}"; do
        cat > "$SANDBOX/modules/$mod.sh" <<EOF
#!/bin/bash
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
source "\$SCRIPT_DIR/lib/common.sh"
echo "MODULE-RAN: $mod"
exit 0
EOF
    done

    # Stub 06 mirrors the real module's contract: generate a secret,
    # persist it via save_config.
    cat > "$SANDBOX/modules/06-postgresql.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/config.sh"
load_config
echo "MODULE-RAN: 06-postgresql"
POSTGRES_PASSWORD="stub-pw-12345"
save_config
exit 0
EOF

    # Stub 07 asserts the secret generated by 06 arrived.
    cat > "$SANDBOX/modules/07-env-generate.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/config.sh"
load_config
echo "MODULE-RAN: 07-env-generate"
if [[ "${POSTGRES_PASSWORD:-}" != "stub-pw-12345" ]]; then
    echo "07: POSTGRES_PASSWORD did not arrive (got: '${POSTGRES_PASSWORD:-}')" >&2
    exit 1
fi
exit 0
EOF

    # Failing verify stub — install.sh runs it with `|| true`, so the
    # completion banner must still appear. Strict mode like the real script.
    cat > "$SANDBOX/verify/verify-install.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
echo "VERIFY-RAN"
exit 1
EOF
}

cleanup() { rm -rf "$SANDBOX"; }
trap 'rm -rf "${SANDBOX:-}"' EXIT

# ─── Tests 1 + 2 + 6: full run, config round-trip, verify tolerance ──────────

make_sandbox
CONF="$SANDBOX/install.conf"
OUTPUT=$(bash "$SANDBOX/install.sh" --non-interactive --config "$CONF" 2>&1)
RC=$?

if [[ $RC -eq 0 ]]; then pass "full run exits 0"; else fail "full run exited $RC"; fi
for mod in "${ALL_MODULES[@]}"; do
    if grep -q "MODULE-RAN: $mod" <<<"$OUTPUT"; then
        pass "module $mod ran"
    else
        fail "module $mod did NOT run"
    fi
done
if grep -q "Installation Complete" <<<"$OUTPUT"; then
    pass "completion banner shown"
else
    fail "completion banner missing"
fi
if grep -q "VERIFY-RAN" <<<"$OUTPUT"; then
    pass "verify script ran (failing verify tolerated)"
else
    fail "verify script did not run"
fi
if grep -q 'POSTGRES_PASSWORD=stub-pw-12345' "$CONF" 2>/dev/null; then
    pass "POSTGRES_PASSWORD persisted to config file"
else
    fail "POSTGRES_PASSWORD missing from config file"
fi
cleanup

# ─── Test 3: failing module stops the run; later modules skipped ─────────────

make_sandbox
CONF="$SANDBOX/install.conf"
cat > "$SANDBOX/modules/05-python-venv.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
echo "MODULE-RAN: 05-python-venv"
echo "boom" >&2
exit 1
EOF
OUTPUT=$(bash "$SANDBOX/install.sh" --non-interactive --config "$CONF" 2>&1)
RC=$?
if [[ $RC -ne 0 ]]; then pass "failed run exits nonzero"; else fail "failed run exited 0"; fi
if grep -q "Installation stopped at module: 05-python-venv" <<<"$OUTPUT"; then
    pass "stop message with resume hint shown"
else
    fail "stop message missing"
fi
if ! grep -q "MODULE-RAN: 06-postgresql" <<<"$OUTPUT"; then
    pass "later modules skipped after failure"
else
    fail "later modules ran after failure"
fi
cleanup

# ─── Test 4: --module single mode propagates exit code ──────────────────────

make_sandbox
CONF="$SANDBOX/install.conf"
cat > "$SANDBOX/modules/05-python-venv.sh" <<'EOF'
#!/bin/bash
exit 7
EOF
bash "$SANDBOX/install.sh" --module 05-python-venv --config "$CONF" >/dev/null 2>&1
RC=$?
if [[ $RC -eq 7 ]]; then
    pass "--module propagates module exit code (7)"
else
    fail "--module exit code was $RC (expected 7)"
fi
cleanup

# ─── Test 5: save_config/load_config round-trip with special characters ─────

make_sandbox
CONF="$SANDBOX/install.conf"
cat > "$SANDBOX/roundtrip.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/config.sh"
ADMIN_PASSWORD='p@ss word$1"x'
save_config
ADMIN_PASSWORD=""
load_config
if [[ "$ADMIN_PASSWORD" == 'p@ss word$1"x' ]]; then
    echo "ROUNDTRIP-OK"
else
    echo "round-trip mismatch: '$ADMIN_PASSWORD'" >&2
    exit 1
fi
EOF
RT_OUTPUT=$(BALUHOST_CONFIG="$CONF" bash "$SANDBOX/roundtrip.sh" 2>&1)
if grep -q "ROUNDTRIP-OK" <<<"$RT_OUTPUT"; then
    pass "config round-trip preserves special characters"
else
    fail "config round-trip broke special characters: $RT_OUTPUT"
fi
cleanup

# ─── Guard: verify-install.sh must not use ((var++)) under set -e ───────────
# ((PASS++)) with PASS=0 evaluates to 0 → exit status 1 → errexit kills the
# script at the first check. Masked while the script was sourced with
# `|| true`; real since install.sh executes it via `bash` (#212 review).

if grep -qE '\(\([A-Za-z_]+\+\+\)\)' "$INSTALL_SRC/verify/verify-install.sh"; then
    fail "verify-install.sh uses ((var++)) — dies under set -e when var is 0"
else
    pass "verify-install.sh free of ((var++)) errexit trap"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]]
