"""
NFS export management service for BaluHost.

Generates /etc/exports.d/baluhost.exports from admin-defined export records and
reloads it via `exportfs -ra`. In dev mode all system commands are no-ops.
"""
import asyncio
import ipaddress
import logging
import os
import re
import tempfile
from pathlib import Path, PurePosixPath
from typing import Optional

from app.core.config import settings
from app.core.database import SessionLocal
from app.models.nfs_export import NfsExport

logger = logging.getLogger(__name__)

NFS_EXPORTS_CONF = "/etc/exports.d/baluhost.exports"

# RFC-1123-ish hostname (also allows single-label names like "host").
_HOSTNAME_RE = re.compile(
    r"^(?=.{1,253}$)"
    r"([a-zA-Z0-9_](?:[a-zA-Z0-9_-]{0,61}[a-zA-Z0-9_])?)"
    r"(\.[a-zA-Z0-9_](?:[a-zA-Z0-9_-]{0,61}[a-zA-Z0-9_])?)*$"
)


def _get_exports_conf_path() -> str:
    """Return the path used for the generated exports file (overridable in tests)."""
    return getattr(settings, "nfs_exports_conf_path", NFS_EXPORTS_CONF)


def validate_clients(clients: str) -> str:
    """Validate a single NFS client spec.

    Accepts '*', an IP address (IPv4 or IPv6), an IP CIDR, or a DNS hostname.
    Returns the trimmed spec. Raises ValueError otherwise.
    """
    spec = (clients or "").strip()
    if not spec:
        raise ValueError("clients must not be empty")
    if spec == "*":
        return spec
    if "/" in spec:
        try:
            ipaddress.ip_network(spec, strict=False)
            return spec
        except ValueError as exc:
            raise ValueError(f"Invalid CIDR for NFS clients: {spec!r}") from exc
    try:
        ipaddress.ip_address(spec)
        return spec
    except ValueError:
        pass
    # If the spec looks like an IP address (all-numeric dotted parts) but failed
    # ip_address() validation, reject it — don't let it slip through as a hostname.
    if all(part.isdigit() for part in spec.split(".")):
        raise ValueError(f"Invalid IP address for NFS clients: {spec!r}")
    # Note: NFS subdomain wildcards like "*.example.com" are intentionally not supported.
    if _HOSTNAME_RE.match(spec):
        return spec
    raise ValueError(f"Invalid NFS client spec: {spec!r}")


def validate_export_path(path: str) -> str:
    """Validate an export path (relative to the storage root); return absolute path.

    Empty string means the storage root itself. Rejects path traversal and any
    path that resolves outside the storage root.
    """
    storage_root = Path(settings.nas_storage_path).expanduser().resolve()
    rel = (path or "").strip().strip("/")
    # The validated path is written verbatim into the exports file (consumed by
    # `exportfs -ra`). Reject control characters and whitespace to prevent
    # injection of extra export lines or broken `path client(opts)` tokenisation.
    if any(ord(c) < 0x20 for c in rel):
        raise ValueError(f"Path contains control characters: {path!r}")
    if " " in rel or "\t" in rel:
        raise ValueError(f"Path contains whitespace: {path!r}")
    if ".." in PurePosixPath(rel).parts:
        raise ValueError(f"Path traversal not allowed: {path!r}")
    abs_path = (storage_root / rel).resolve()
    if abs_path != storage_root and storage_root not in abs_path.parents:
        raise ValueError(f"Export path escapes storage root: {path!r}")
    return str(abs_path)


async def _run_cmd(cmd: list[str]) -> tuple[int, str, str]:
    """Run a system command (no shell). Returns (returncode, stdout, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdin=asyncio.subprocess.DEVNULL,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, err = await proc.communicate()
    return proc.returncode or 0, out.decode(errors="replace"), err.decode(errors="replace")


async def regenerate_exports_config() -> bool:
    """Regenerate /etc/exports.d/baluhost.exports from enabled DB exports."""
    if settings.is_dev_mode:
        logger.info("[DEV] Mock regenerate_exports_config()")
        return True

    db = SessionLocal()
    try:
        exports = (
            db.query(NfsExport)
            .filter(NfsExport.enabled == True)  # noqa: E712
            .order_by(NfsExport.id)
            .all()
        )
    finally:
        db.close()

    lines = ["# Auto-generated by BaluHost — do not edit manually", ""]
    for exp in exports:
        abs_path = validate_export_path(exp.path)
        client_spec = validate_clients(exp.clients)
        mode = "ro" if exp.read_only else "rw"
        squash = "root_squash" if exp.root_squash else "no_root_squash"
        opts = f"{mode},{squash},sync,no_subtree_check,fsid={exp.id}"
        lines.append(f"{abs_path} {client_spec}({opts})")
    lines.append("")

    conf_path = _get_exports_conf_path()
    content = "\n".join(lines)
    try:
        dir_path = os.path.dirname(conf_path)
        fd, tmp_path = tempfile.mkstemp(dir=dir_path, prefix=".baluhost-exports-", suffix=".tmp")
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.rename(tmp_path, conf_path)
        logger.info("Regenerated NFS exports config (%d exports)", len(exports))
        return True
    except OSError as exc:
        logger.error("Failed to write NFS exports config: %s", exc)
        return False


async def apply_exports() -> bool:
    """Reload all NFS exports via `exportfs -ra`."""
    if settings.is_dev_mode:
        logger.info("[DEV] Mock apply_exports()")
        return True
    rc, _, stderr = await _run_cmd(["sudo", "exportfs", "-ra"])
    if rc != 0:
        logger.error("exportfs -ra failed: %s", stderr)
        return False
    logger.info("NFS exports reloaded")
    return True


async def get_nfs_status() -> dict:
    """Return {is_running, version, exports_count}."""
    db = SessionLocal()
    try:
        count = db.query(NfsExport).filter(NfsExport.enabled == True).count()  # noqa: E712
    finally:
        db.close()

    if settings.is_dev_mode:
        return {"is_running": False, "version": "dev-mode", "exports_count": count}

    rc, _, _ = await _run_cmd(["systemctl", "is-active", "nfs-server"])
    is_running = rc == 0
    if not is_running:
        rc2, _, _ = await _run_cmd(["pgrep", "nfsd"])
        is_running = rc2 == 0

    version: Optional[str] = None
    return {"is_running": is_running, "version": version, "exports_count": count}
