#!/bin/bash
# BaluHost - Avahi mDNS Installation Script
# Installs and configures Avahi daemon for baluhost.local hostname resolution

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
HOSTNAME="baluhost"
NETWORK_INTERFACES="eth0,wlan0"  # Common interfaces, can be customized

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

# Detect Linux distribution
detect_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "$ID"
    elif [ -f /etc/debian_version ]; then
        echo "debian"
    elif [ -f /etc/redhat-release ]; then
        echo "rhel"
    else
        echo "unknown"
    fi
}

DISTRO=$(detect_distro)
log_info "Detected distribution: $DISTRO"

# Install Avahi based on distribution
install_avahi() {
    log_info "Installing Avahi daemon..."

    case "$DISTRO" in
        ubuntu|debian|raspbian)
            apt-get update
            apt-get install -y avahi-daemon avahi-utils
            ;;
        fedora|rhel|centos)
            dnf install -y avahi avahi-tools || yum install -y avahi avahi-tools
            ;;
        arch|manjaro)
            pacman -Sy --noconfirm avahi nss-mdns
            ;;
        *)
            log_error "Unsupported distribution: $DISTRO"
            log_info "Please install avahi-daemon manually"
            exit 1
            ;;
    esac

    log_info "Avahi daemon installed successfully"
}

# Configure Avahi daemon
configure_avahi() {
    log_info "Configuring Avahi daemon..."

    # Backup original config if it exists
    if [ -f /etc/avahi/avahi-daemon.conf ]; then
        cp /etc/avahi/avahi-daemon.conf /etc/avahi/avahi-daemon.conf.backup
        log_info "Backed up original config to /etc/avahi/avahi-daemon.conf.backup"
    fi

    # Detect active network interfaces
    ACTIVE_INTERFACES=$(ip -o link show | awk -F': ' '{print $2}' | grep -v '^lo$' | tr '\n' ',' | sed 's/,$//')

    if [ -z "$ACTIVE_INTERFACES" ]; then
        log_warn "No active network interfaces detected, using default: $NETWORK_INTERFACES"
    else
        NETWORK_INTERFACES="$ACTIVE_INTERFACES"
        log_info "Detected network interfaces: $NETWORK_INTERFACES"
    fi

    # Write Avahi daemon configuration
    cat > /etc/avahi/avahi-daemon.conf <<EOF
# Avahi daemon configuration for BaluHost
# Generated by install-avahi.sh

[server]
host-name=$HOSTNAME
domain-name=local
use-ipv4=yes
use-ipv6=yes
allow-interfaces=$NETWORK_INTERFACES
deny-interfaces=docker0,veth*
enable-dbus=yes
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes
publish-dns-servers=no
publish-resolv-conf-dns-servers=no
publish-aaaa-on-ipv4=yes
publish-a-on-ipv6=no

[reflector]
enable-reflector=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=768
rlimit-stack=4194304
rlimit-nproc=3
EOF

    log_info "Avahi daemon configured with hostname: $HOSTNAME"
}

# Create Avahi service definition for BaluHost
create_service_file() {
    log_info "Creating Avahi service definition..."

    # Copy service file from deploy/avahi if it exists
    if [ -f "$(dirname "$0")/../avahi/baluhost.service" ]; then
        cp "$(dirname "$0")/../avahi/baluhost.service" /etc/avahi/services/baluhost.service
        log_info "Copied baluhost.service from deploy/avahi/"
    else
        # Create service file manually
        cat > /etc/avahi/services/baluhost.service <<EOF
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">BaluHost on %h</name>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
    <txt-record>path=/</txt-record>
  </service>
  <service>
    <type>_https._tcp</type>
    <port>443</port>
  </service>
</service-group>
EOF
        log_info "Created baluhost.service manually"
    fi
}

# Configure firewall (if applicable)
configure_firewall() {
    log_info "Configuring firewall for mDNS..."

    # Check if firewalld is active
    if systemctl is-active --quiet firewalld; then
        firewall-cmd --permanent --add-service=mdns
        firewall-cmd --reload
        log_info "Firewalld configured to allow mDNS (UDP 5353)"
    # Check if ufw is active
    elif systemctl is-active --quiet ufw; then
        ufw allow 5353/udp
        log_info "UFW configured to allow mDNS (UDP 5353)"
    else
        log_warn "No firewall detected, skipping firewall configuration"
        log_info "If you have a firewall, ensure UDP port 5353 is allowed"
    fi
}

# Enable and start Avahi daemon
start_avahi() {
    log_info "Enabling and starting Avahi daemon..."

    systemctl enable avahi-daemon
    systemctl restart avahi-daemon

    # Wait for service to start
    sleep 2

    if systemctl is-active --quiet avahi-daemon; then
        log_info "Avahi daemon started successfully"
    else
        log_error "Avahi daemon failed to start"
        systemctl status avahi-daemon
        exit 1
    fi
}

# Test mDNS resolution
test_mdns() {
    log_info "Testing mDNS resolution..."

    # Wait for Avahi to publish
    sleep 3

    # Test with avahi-browse
    if command -v avahi-browse &> /dev/null; then
        log_info "Available mDNS services:"
        avahi-browse -a -t -r | head -n 20
    fi

    # Test hostname resolution
    if command -v avahi-resolve &> /dev/null; then
        log_info "Testing hostname resolution..."
        RESOLVED=$(avahi-resolve -n ${HOSTNAME}.local 2>&1)
        if echo "$RESOLVED" | grep -q "Failed"; then
            log_warn "Could not resolve ${HOSTNAME}.local yet (may take a few seconds)"
        else
            log_info "Successfully resolved: $RESOLVED"
        fi
    fi

    log_info "You can test manually with: ping ${HOSTNAME}.local"
}

# Main installation flow
main() {
    log_info "Starting BaluHost Avahi installation..."
    log_info "This will configure hostname: ${HOSTNAME}.local"

    # Check if Avahi is already installed
    if command -v avahi-daemon &> /dev/null; then
        log_warn "Avahi daemon is already installed"
        read -p "Do you want to reconfigure it? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Skipping installation"
            exit 0
        fi
    else
        install_avahi
    fi

    configure_avahi
    create_service_file
    configure_firewall
    start_avahi
    test_mdns

    log_info ""
    log_info "=========================================="
    log_info "✅ Avahi installation completed!"
    log_info "=========================================="
    log_info ""
    log_info "BaluHost is now accessible via:"
    log_info "  - http://${HOSTNAME}.local"
    log_info "  - https://${HOSTNAME}.local (if SSL configured)"
    log_info ""
    log_info "Test with:"
    log_info "  ping ${HOSTNAME}.local"
    log_info "  avahi-browse -a -t"
    log_info ""
    log_info "Note: Windows clients need Bonjour Print Services"
    log_info "      or manual hosts file entry for .local resolution"
    log_info ""
}

# Run main function
main
