#!/bin/bash
# Install AMD GPU sysfs permission rule for BaluHost service user.
#
# Why: BaluHost's GPU power manager writes to
#   /sys/class/drm/card*/device/power_dpm_force_performance_level
#   /sys/class/drm/card*/device/pp_power_profile_mode
# These default to root:root 0644 and the service runs as a non-root user,
# so writes fail with "Permission denied".
#
# What this does:
#   1. Drops a udev rule into /etc/udev/rules.d/70-baluhost-amd-gpu.rules
#      that chgrp's the AMD power sysfs nodes to "video" and adds g+w on
#      every drm-card add/change event.
#   2. Adds the BaluHost service user to the "video" group.
#   3. Reloads udev and re-triggers drm subsystem events so the new
#      permissions apply immediately (no reboot needed).
#   4. Restarts the BaluHost backend so it picks up the new group
#      membership.
#
# Run as root.

set -euo pipefail

BALUHOST_USER="${BALUHOST_USER:-sven}"
RULE_PATH="/etc/udev/rules.d/70-baluhost-amd-gpu.rules"

if [[ "$EUID" -ne 0 ]]; then
    echo "ERROR: must run as root (use sudo)." >&2
    exit 1
fi

# Sanity check: AMD card present?
if ! ls /sys/class/drm/card*/device/power_dpm_force_performance_level >/dev/null 2>&1 \
   && ! ls /sys/class/drm/card*/device/pp_power_profile_mode >/dev/null 2>&1; then
    echo "WARN: no AMDGPU sysfs power nodes found. Aborting (nothing to do)." >&2
    exit 0
fi

# 1. Write the rule
cat >"$RULE_PATH" <<EOF
# BaluHost AMD GPU power sysfs permission grant.
# Generated by install-amd-gpu-permissions.sh — do not edit by hand.
# See docs/deployment/AMD_GPU_PERMISSIONS.de.md for context.
ACTION=="add|change", SUBSYSTEM=="drm", KERNEL=="card[0-9]*", \\
    RUN+="/bin/sh -c 'for f in /sys/class/drm/%k/device/power_dpm_force_performance_level /sys/class/drm/%k/device/pp_power_profile_mode; do [ -e \"\$f\" ] && chgrp video \"\$f\" && chmod g+w \"\$f\"; done'"
EOF
chmod 644 "$RULE_PATH"
echo "  OK  installed udev rule: $RULE_PATH"

# 2. Add user to video group (no-op if already a member)
if id -nG "$BALUHOST_USER" | tr ' ' '\n' | grep -qx video; then
    echo "  OK  $BALUHOST_USER already in 'video' group"
else
    usermod -aG video "$BALUHOST_USER"
    echo "  OK  added $BALUHOST_USER to 'video' group"
fi

# 3. Reload udev and re-trigger drm so the rule takes effect now
udevadm control --reload-rules
udevadm trigger --subsystem-match=drm
echo "  OK  udev rules reloaded and triggered"

# 4. Verify permissions
sleep 1
if find /sys/class/drm -maxdepth 3 \( -name power_dpm_force_performance_level -o -name pp_power_profile_mode \) -perm -g+w 2>/dev/null | grep -q .; then
    echo "  OK  group-writable bit confirmed on AMD power sysfs nodes"
else
    echo "  WARN  group-writable bit not yet visible — udev may apply on next add/change event"
fi

# 5. Restart the backend so its process picks up the new group membership
if systemctl is-active --quiet baluhost-backend; then
    systemctl restart baluhost-backend
    echo "  OK  baluhost-backend restarted"
else
    echo "  INFO  baluhost-backend not running — start it manually when ready"
fi

echo
echo "Done. Verify in the UI: GPU Power Management card should now show"
echo "WRITE PERMISSION: ok (instead of: missing)."
echo
echo "Or via API:"
echo "  curl -s -H 'Authorization: Bearer <admin-jwt>' \\"
echo "    http://localhost:8000/api/gpu-power/status | jq '.has_write_permission'"
