#!/bin/bash
# BaluHost - Complete Hostname Setup Script
# One-click setup for baluhost.local network discovery
#
# This script:
# 1. Installs and configures Avahi for mDNS/Bonjour
# 2. Configures Nginx reverse proxy (if needed)
# 3. Tests the configuration
# 4. Displays access instructions

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
HOSTNAME="baluhost"
BACKEND_PORT=8000
FRONTEND_PORT=5173
WEBDAV_PORT=8080
HTTP_PORT=80
HTTPS_PORT=443

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Detect system IP address
get_local_ip() {
    ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -n 1
}

# Step 1: Install and configure Avahi
setup_avahi() {
    log_step "Step 1: Installing and configuring Avahi for mDNS..."

    if [ -f "$SCRIPT_DIR/install-avahi.sh" ]; then
        bash "$SCRIPT_DIR/install-avahi.sh"
    else
        log_error "install-avahi.sh not found in $SCRIPT_DIR"
        exit 1
    fi

    log_info "Avahi setup completed"
}

# Step 2: Configure Nginx (optional, check if needed)
setup_nginx() {
    log_step "Step 2: Checking Nginx configuration..."

    if ! command -v nginx &> /dev/null; then
        log_warn "Nginx not installed. Skipping reverse proxy setup."
        log_info "You can access BaluHost directly on ports $BACKEND_PORT and $FRONTEND_PORT"
        return
    fi

    # Check if baluhost.conf exists
    if [ ! -f "$DEPLOY_DIR/nginx/baluhost.conf" ]; then
        log_warn "Nginx config not found at $DEPLOY_DIR/nginx/baluhost.conf"
        log_info "Skipping Nginx configuration"
        return
    fi

    log_info "Found Nginx configuration"

    # Get local IP for config replacement
    LOCAL_IP=$(get_local_ip)

    if [ -z "$LOCAL_IP" ]; then
        log_warn "Could not detect local IP address"
        LOCAL_IP="192.168.1.100"  # Fallback
    fi

    log_info "Detected local IP: $LOCAL_IP"

    # Create modified config
    TEMP_CONF="/tmp/baluhost.conf"
    cp "$DEPLOY_DIR/nginx/baluhost.conf" "$TEMP_CONF"

    # Replace placeholders
    sed -i "s/YOUR_DOMAIN_HERE/baluhost baluhost.local $LOCAL_IP/g" "$TEMP_CONF"
    sed -i "s/YOUR_IP_HERE/$LOCAL_IP/g" "$TEMP_CONF"

    # Ask user if they want to install Nginx config
    read -p "Do you want to install Nginx reverse proxy configuration? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Copy config to Nginx sites-available
        cp "$TEMP_CONF" /etc/nginx/sites-available/baluhost.conf

        # Enable site
        ln -sf /etc/nginx/sites-available/baluhost.conf /etc/nginx/sites-enabled/baluhost.conf

        # Test Nginx config
        if nginx -t; then
            systemctl reload nginx
            log_info "Nginx configuration installed and reloaded"
        else
            log_error "Nginx configuration test failed"
            rm /etc/nginx/sites-enabled/baluhost.conf
            return 1
        fi
    else
        log_info "Skipping Nginx configuration"
    fi

    rm -f "$TEMP_CONF"
}

# Step 3: Update backend config (if needed)
update_backend_config() {
    log_step "Step 3: Checking backend configuration..."

    # Check if .env file exists in backend directory
    BACKEND_DIR="$DEPLOY_DIR/../backend"
    ENV_FILE="$BACKEND_DIR/.env"

    if [ ! -f "$ENV_FILE" ]; then
        log_info "Creating .env file with mDNS hostname configuration..."
        cat > "$ENV_FILE" <<EOF
# BaluHost Environment Configuration
# Generated by setup-hostname.sh

# Network Discovery (mDNS/Bonjour)
MDNS_HOSTNAME=$HOSTNAME

# Server Configuration
NAS_MODE=prod
EOF
        log_info "Created $ENV_FILE"
    else
        # Check if MDNS_HOSTNAME is already set
        if grep -q "MDNS_HOSTNAME" "$ENV_FILE"; then
            log_info "MDNS_HOSTNAME already configured in .env"
        else
            echo "MDNS_HOSTNAME=$HOSTNAME" >> "$ENV_FILE"
            log_info "Added MDNS_HOSTNAME to $ENV_FILE"
        fi
    fi
}

# Step 4: Test configuration
test_configuration() {
    log_step "Step 4: Testing configuration..."

    # Wait for services to settle
    sleep 3

    # Test 1: Check if Avahi is running
    if systemctl is-active --quiet avahi-daemon; then
        log_info "✅ Avahi daemon is running"
    else
        log_error "❌ Avahi daemon is not running"
        return 1
    fi

    # Test 2: Check mDNS resolution
    if command -v avahi-resolve &> /dev/null; then
        RESOLVED=$(avahi-resolve -n ${HOSTNAME}.local 2>&1)
        if echo "$RESOLVED" | grep -q "Failed"; then
            log_warn "⚠️  Could not resolve ${HOSTNAME}.local (may take a few seconds)"
        else
            log_info "✅ Hostname resolution works: $RESOLVED"
        fi
    fi

    # Test 3: Check if backend is running
    LOCAL_IP=$(get_local_ip)
    if curl -s -o /dev/null -w "%{http_code}" "http://$LOCAL_IP:$BACKEND_PORT/api/health" | grep -q "200\|404"; then
        log_info "✅ Backend is reachable on port $BACKEND_PORT"
    else
        log_warn "⚠️  Backend not reachable on port $BACKEND_PORT (is it running?)"
    fi

    # Test 4: Check Nginx (if installed)
    if command -v nginx &> /dev/null && systemctl is-active --quiet nginx; then
        if curl -s -o /dev/null -w "%{http_code}" "http://$LOCAL_IP:$HTTP_PORT" | grep -q "200\|301\|302"; then
            log_info "✅ Nginx reverse proxy is working on port $HTTP_PORT"
        else
            log_warn "⚠️  Nginx is running but not responding on port $HTTP_PORT"
        fi
    fi
}

# Display final instructions
show_instructions() {
    LOCAL_IP=$(get_local_ip)

    echo ""
    echo "=========================================="
    log_info "🎉 BaluHost Hostname Setup Complete!"
    echo "=========================================="
    echo ""
    log_info "Access BaluHost via:"
    echo ""

    if command -v nginx &> /dev/null && systemctl is-active --quiet nginx; then
        echo -e "  ${GREEN}Primary (via Nginx):${NC}"
        echo "    http://${HOSTNAME}.local"
        echo "    http://$LOCAL_IP"
        echo ""
        echo -e "  ${YELLOW}Direct access:${NC}"
        echo "    Backend:  http://$LOCAL_IP:$BACKEND_PORT"
        echo "    Frontend: http://$LOCAL_IP:$FRONTEND_PORT"
        echo "    WebDAV:   http://$LOCAL_IP:$WEBDAV_PORT/webdav"
    else
        echo -e "  ${GREEN}Direct access:${NC}"
        echo "    Backend:  http://${HOSTNAME}.local:$BACKEND_PORT"
        echo "    Backend:  http://$LOCAL_IP:$BACKEND_PORT"
        echo "    Frontend: http://${HOSTNAME}.local:$FRONTEND_PORT"
        echo "    Frontend: http://$LOCAL_IP:$FRONTEND_PORT"
        echo "    WebDAV:   http://${HOSTNAME}.local:$WEBDAV_PORT/webdav"
    fi

    echo ""
    echo "=========================================="
    log_info "Testing Commands:"
    echo "=========================================="
    echo ""
    echo "  Test hostname resolution:"
    echo "    ping ${HOSTNAME}.local"
    echo ""
    echo "  Browse available mDNS services:"
    echo "    avahi-browse -a -t"
    echo ""
    echo "  Check specific service:"
    echo "    avahi-browse -r _baluhost._tcp"
    echo ""

    echo "=========================================="
    log_info "Client Setup:"
    echo "=========================================="
    echo ""
    echo -e "  ${GREEN}Mac/Linux:${NC} Works automatically (native mDNS support)"
    echo ""
    echo -e "  ${YELLOW}Windows:${NC} Choose one option:"
    echo "    1. Install Bonjour Print Services (recommended)"
    echo "       Download: https://support.apple.com/kb/DL999"
    echo ""
    echo "    2. Add to hosts file:"
    echo "       File: C:\\Windows\\System32\\drivers\\etc\\hosts"
    echo "       Add:  $LOCAL_IP  baluhost baluhost.local"
    echo ""
    echo -e "  ${BLUE}Smartphones:${NC}"
    echo "    iOS:     Native support (works automatically)"
    echo "    Android: Varies by version (5.0+ usually supported)"
    echo ""

    echo "=========================================="
    log_info "Next Steps:"
    echo "=========================================="
    echo ""
    echo "  1. Restart BaluHost backend to apply hostname changes"
    echo "  2. Test access from a client device"
    echo "  3. Configure SSL/TLS for HTTPS (see docs/DEPLOYMENT.md)"
    echo ""
}

# Main setup flow
main() {
    log_info "Starting BaluHost complete hostname setup..."
    log_info "Target hostname: ${HOSTNAME}.local"
    echo ""

    check_root
    setup_avahi
    echo ""
    setup_nginx
    echo ""
    update_backend_config
    echo ""
    test_configuration
    echo ""
    show_instructions
}

# Run main function
main
