"""Add sync state, metadata, and versioning tables

Revision ID: 27cc09d8d50c
Revises: fc75e3fa9c96
Create Date: 2025-12-05 22:12:43.937840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cc09d8d50c'
down_revision: Union[str, Sequence[str], None] = 'fc75e3fa9c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
