"""add core uptime windows and master toggle

Revision ID: 48b9f26caec2
Revises: c9e1lifecycle01
Create Date: 2026-05-01 21:57:37.446206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b9f26caec2'
down_revision: Union[str, Sequence[str], None] = 'c9e1lifecycle01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sleep_config',
        sa.Column('core_uptime_enabled', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.create_table('core_uptime_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('weekdays', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_uptime_windows_id'), 'core_uptime_windows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_uptime_windows_id'), table_name='core_uptime_windows')
    op.drop_table('core_uptime_windows')
    op.drop_column('sleep_config', 'core_uptime_enabled')
    # ### end Alembic commands ###
