"""add gpu power tables

Revision ID: b42843d45987
Revises: e828c7b306d5
Create Date: 2026-04-30 21:30:35.265725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42843d45987'
down_revision: Union[str, Sequence[str], None] = 'e828c7b306d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_power_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpu_power_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('previous_state', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('power_watts_at_transition', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gpu_power_log_state_ts', 'gpu_power_log', ['state', 'timestamp'], unique=False)
    op.create_index(op.f('ix_gpu_power_log_id'), 'gpu_power_log', ['id'], unique=False)
    op.create_index(op.f('ix_gpu_power_log_state'), 'gpu_power_log', ['state'], unique=False)
    op.create_index(op.f('ix_gpu_power_log_timestamp'), 'gpu_power_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_power_log_timestamp'), table_name='gpu_power_log')
    op.drop_index(op.f('ix_gpu_power_log_state'), table_name='gpu_power_log')
    op.drop_index(op.f('ix_gpu_power_log_id'), table_name='gpu_power_log')
    op.drop_index('idx_gpu_power_log_state_ts', table_name='gpu_power_log')
    op.drop_table('gpu_power_log')
    op.drop_table('gpu_power_config')
    # ### end Alembic commands ###
