"""add status bar tables

Revision ID: b48340a96a5a
Revises: 37ae61688702
Create Date: 2026-05-28 20:04:53.110222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48340a96a5a'
down_revision: Union[str, Sequence[str], None] = '37ae61688702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_bar_pill_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pill_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pill_id')
    )
    op.create_index(op.f('ix_status_bar_pill_config_id'), 'status_bar_pill_config', ['id'], unique=False)
    op.create_table('status_bar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_bottom_upload', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_bar_settings')
    op.drop_index(op.f('ix_status_bar_pill_config_id'), table_name='status_bar_pill_config')
    op.drop_table('status_bar_pill_config')
    # ### end Alembic commands ###
