"""add system_lifecycle_events table

Revision ID: be39e06e62e8
Revises: b9f2e3a1c7d4
Create Date: 2026-04-30 17:07:51.751002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be39e06e62e8'
down_revision: Union[str, Sequence[str], None] = 'b9f2e3a1c7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_lifecycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lifecycle_type_ts', 'system_lifecycle_events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_system_lifecycle_events_event_type'), 'system_lifecycle_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_lifecycle_events_id'), 'system_lifecycle_events', ['id'], unique=False)
    op.create_index(op.f('ix_system_lifecycle_events_timestamp'), 'system_lifecycle_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_lifecycle_events_timestamp'), table_name='system_lifecycle_events')
    op.drop_index(op.f('ix_system_lifecycle_events_id'), table_name='system_lifecycle_events')
    op.drop_index(op.f('ix_system_lifecycle_events_event_type'), table_name='system_lifecycle_events')
    op.drop_index('ix_lifecycle_type_ts', table_name='system_lifecycle_events')
    op.drop_table('system_lifecycle_events')
    # ### end Alembic commands ###
