"""Add RefreshToken table for token revocation

Revision ID: c7fbef10fbee
Revises: b5a0a9df91ea
Create Date: 2026-01-12 22:08:35.018454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7fbef10fbee'
down_revision: Union[str, Sequence[str], None] = 'b5a0a9df91ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_ip', sa.String(length=45), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_tokens', 'refresh_tokens', ['device_id', 'revoked'], unique=False)
    op.create_index('idx_expired_tokens', 'refresh_tokens', ['expires_at', 'revoked'], unique=False)
    op.create_index('idx_user_active_tokens', 'refresh_tokens', ['user_id', 'revoked', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sync_metadata_file_metadata_id'), table_name='sync_metadata')
    op.drop_index(op.f('ix_sync_metadata_id'), table_name='sync_metadata')
    op.drop_index(op.f('ix_sync_metadata_sync_state_id'), table_name='sync_metadata')
    op.drop_table('sync_metadata')
    op.drop_index(op.f('ix_sync_file_versions_file_metadata_id'), table_name='sync_file_versions')
    op.drop_index(op.f('ix_sync_file_versions_id'), table_name='sync_file_versions')
    op.drop_table('sync_file_versions')
    op.drop_index(op.f('ix_selective_syncs_id'), table_name='selective_syncs')
    op.drop_index(op.f('ix_selective_syncs_user_id'), table_name='selective_syncs')
    op.drop_table('selective_syncs')
    op.drop_index(op.f('ix_sync_schedules_id'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_user_id'), table_name='sync_schedules')
    op.drop_table('sync_schedules')
    op.drop_index(op.f('ix_chunked_uploads_id'), table_name='chunked_uploads')
    op.drop_index(op.f('ix_chunked_uploads_upload_id'), table_name='chunked_uploads')
    op.drop_index(op.f('ix_chunked_uploads_user_id'), table_name='chunked_uploads')
    op.drop_table('chunked_uploads')
    op.drop_index(op.f('ix_sync_states_device_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_user_id'), table_name='sync_states')
    op.drop_table('sync_states')
    op.drop_index(op.f('ix_sync_bandwidth_limits_id'), table_name='sync_bandwidth_limits')
    op.drop_index(op.f('ix_sync_bandwidth_limits_user_id'), table_name='sync_bandwidth_limits')
    op.drop_table('sync_bandwidth_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_bandwidth_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upload_speed_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('download_speed_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('throttle_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('throttle_start_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('throttle_end_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sync_bandwidth_limits_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_bandwidth_limits_pkey'))
    )
    op.create_index(op.f('ix_sync_bandwidth_limits_user_id'), 'sync_bandwidth_limits', ['user_id'], unique=True)
    op.create_index(op.f('ix_sync_bandwidth_limits_id'), 'sync_bandwidth_limits', ['id'], unique=False)
    op.create_table('sync_states',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sync_states_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_sync', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_change_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sync_states_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sync_states_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sync_states_user_id'), 'sync_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_states_id'), 'sync_states', ['id'], unique=False)
    op.create_index(op.f('ix_sync_states_device_id'), 'sync_states', ['device_id'], unique=True)
    op.create_table('chunked_uploads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('total_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_chunks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resume_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], name=op.f('chunked_uploads_file_metadata_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chunked_uploads_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chunked_uploads_pkey'))
    )
    op.create_index(op.f('ix_chunked_uploads_user_id'), 'chunked_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_chunked_uploads_upload_id'), 'chunked_uploads', ['upload_id'], unique=True)
    op.create_index(op.f('ix_chunked_uploads_id'), 'chunked_uploads', ['id'], unique=False)
    op.create_table('sync_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('schedule_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('time_of_day', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sync_deletions', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('resolve_conflicts', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sync_schedules_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_schedules_pkey'))
    )
    op.create_index(op.f('ix_sync_schedules_user_id'), 'sync_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_id'), 'sync_schedules', ['id'], unique=False)
    op.create_table('selective_syncs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('folder_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('include_subfolders', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('selective_syncs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('selective_syncs_pkey'))
    )
    op.create_index(op.f('ix_selective_syncs_user_id'), 'selective_syncs', ['user_id'], unique=False)
    op.create_index(op.f('ix_selective_syncs_id'), 'selective_syncs', ['id'], unique=False)
    op.create_table('sync_file_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('sync_file_versions_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], name=op.f('sync_file_versions_file_metadata_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_file_versions_pkey'))
    )
    op.create_index(op.f('ix_sync_file_versions_id'), 'sync_file_versions', ['id'], unique=False)
    op.create_index(op.f('ix_sync_file_versions_file_metadata_id'), 'sync_file_versions', ['file_metadata_id'], unique=False)
    op.create_table('sync_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sync_state_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sync_modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('server_modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('conflict_detected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('conflict_resolution', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], name=op.f('sync_metadata_file_metadata_id_fkey')),
    sa.ForeignKeyConstraint(['sync_state_id'], ['sync_states.id'], name=op.f('sync_metadata_sync_state_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_metadata_pkey'))
    )
    op.create_index(op.f('ix_sync_metadata_sync_state_id'), 'sync_metadata', ['sync_state_id'], unique=False)
    op.create_index(op.f('ix_sync_metadata_id'), 'sync_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_sync_metadata_file_metadata_id'), 'sync_metadata', ['file_metadata_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.drop_index('idx_user_active_tokens', table_name='refresh_tokens')
    op.drop_index('idx_expired_tokens', table_name='refresh_tokens')
    op.drop_index('idx_device_tokens', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
