"""add always_awake to sleep_config

Revision ID: d45e605bfc4d
Revises: gpu_power_mw_2026_05_03
Create Date: 2026-05-07 22:07:28.588818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45e605bfc4d'
down_revision: Union[str, Sequence[str], None] = 'gpu_power_mw_2026_05_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_config', sa.Column('always_awake_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('sleep_config', sa.Column('always_awake_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep_config', 'always_awake_until')
    op.drop_column('sleep_config', 'always_awake_enabled')
    # ### end Alembic commands ###
