"""add user_power_permissions table

Revision ID: deb715622471
Revises: 73092035312b
Create Date: 2026-04-02 18:00:07.675637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb715622471'
down_revision: Union[str, Sequence[str], None] = '73092035312b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_power_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_soft_sleep', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_wake', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_suspend', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('can_wol', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_power_permissions_id'), 'user_power_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_power_permissions_user_id'), 'user_power_permissions', ['user_id'], unique=True)
    op.drop_index(op.f('ix_sync_file_versions_file_metadata_id'), table_name='sync_file_versions')
    op.drop_index(op.f('ix_sync_file_versions_id'), table_name='sync_file_versions')
    op.drop_table('sync_file_versions')
    op.drop_index(op.f('ix_chunked_uploads_id'), table_name='chunked_uploads')
    op.drop_index(op.f('ix_chunked_uploads_upload_id'), table_name='chunked_uploads')
    op.drop_index(op.f('ix_chunked_uploads_user_id'), table_name='chunked_uploads')
    op.drop_table('chunked_uploads')
    op.drop_index(op.f('ix_selective_syncs_id'), table_name='selective_syncs')
    op.drop_index(op.f('ix_selective_syncs_user_id'), table_name='selective_syncs')
    op.drop_table('selective_syncs')
    op.drop_index(op.f('ix_sync_schedules_id'), table_name='sync_schedules')
    op.drop_index(op.f('ix_sync_schedules_user_id'), table_name='sync_schedules')
    op.drop_table('sync_schedules')
    op.drop_index(op.f('ix_sync_bandwidth_limits_id'), table_name='sync_bandwidth_limits')
    op.drop_index(op.f('ix_sync_bandwidth_limits_user_id'), table_name='sync_bandwidth_limits')
    op.drop_table('sync_bandwidth_limits')
    op.drop_index(op.f('ix_sync_metadata_file_metadata_id'), table_name='sync_metadata')
    op.drop_index(op.f('ix_sync_metadata_id'), table_name='sync_metadata')
    op.drop_index(op.f('ix_sync_metadata_sync_state_id'), table_name='sync_metadata')
    op.drop_table('sync_metadata')
    op.drop_index(op.f('ix_sync_states_device_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_id'), table_name='sync_states')
    op.drop_index(op.f('ix_sync_states_user_id'), table_name='sync_states')
    op.drop_table('sync_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_sync', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_change_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_states_user_id'), 'sync_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_states_id'), 'sync_states', ['id'], unique=False)
    op.create_index(op.f('ix_sync_states_device_id'), 'sync_states', ['device_id'], unique=1)
    op.create_table('sync_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), nullable=False),
    sa.Column('sync_state_id', sa.INTEGER(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('local_modified_at', sa.DATETIME(), nullable=False),
    sa.Column('sync_modified_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('server_modified_at', sa.DATETIME(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('conflict_detected', sa.BOOLEAN(), nullable=False),
    sa.Column('conflict_resolution', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], ),
    sa.ForeignKeyConstraint(['sync_state_id'], ['sync_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_metadata_sync_state_id'), 'sync_metadata', ['sync_state_id'], unique=False)
    op.create_index(op.f('ix_sync_metadata_id'), 'sync_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_sync_metadata_file_metadata_id'), 'sync_metadata', ['file_metadata_id'], unique=False)
    op.create_table('sync_bandwidth_limits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('upload_speed_limit', sa.INTEGER(), nullable=True),
    sa.Column('download_speed_limit', sa.INTEGER(), nullable=True),
    sa.Column('throttle_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('throttle_start_hour', sa.INTEGER(), nullable=False),
    sa.Column('throttle_end_hour', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_bandwidth_limits_user_id'), 'sync_bandwidth_limits', ['user_id'], unique=1)
    op.create_index(op.f('ix_sync_bandwidth_limits_id'), 'sync_bandwidth_limits', ['id'], unique=False)
    op.create_table('sync_schedules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('schedule_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('time_of_day', sa.VARCHAR(length=5), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sync_deletions', sa.BOOLEAN(), nullable=False),
    sa.Column('resolve_conflicts', sa.VARCHAR(length=20), nullable=False),
    sa.Column('auto_vpn', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('last_run_at', sa.DATETIME(), nullable=True),
    sa.Column('next_run_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_schedules_user_id'), 'sync_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_sync_schedules_id'), 'sync_schedules', ['id'], unique=False)
    op.create_table('selective_syncs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('folder_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('include_subfolders', sa.BOOLEAN(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selective_syncs_user_id'), 'selective_syncs', ['user_id'], unique=False)
    op.create_index(op.f('ix_selective_syncs_id'), 'selective_syncs', ['id'], unique=False)
    op.create_table('chunked_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('upload_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('total_size', sa.BIGINT(), nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_bytes', sa.BIGINT(), nullable=False),
    sa.Column('completed_chunks', sa.INTEGER(), nullable=False),
    sa.Column('total_chunks', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('resume_token', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunked_uploads_user_id'), 'chunked_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_chunked_uploads_upload_id'), 'chunked_uploads', ['upload_id'], unique=1)
    op.create_index(op.f('ix_chunked_uploads_id'), 'chunked_uploads', ['id'], unique=False)
    op.create_table('sync_file_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_metadata_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=False),
    sa.Column('change_reason', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_metadata_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_file_versions_id'), 'sync_file_versions', ['id'], unique=False)
    op.create_index(op.f('ix_sync_file_versions_file_metadata_id'), 'sync_file_versions', ['file_metadata_id'], unique=False)
    op.drop_index(op.f('ix_user_power_permissions_user_id'), table_name='user_power_permissions')
    op.drop_index(op.f('ix_user_power_permissions_id'), table_name='user_power_permissions')
    op.drop_table('user_power_permissions')
    # ### end Alembic commands ###
