"""add gpu_samples table

Revision ID: e828c7b306d5
Revises: be39e06e62e8
Create Date: 2026-04-30 18:17:23.750090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e828c7b306d5'
down_revision: Union[str, Sequence[str], None] = 'be39e06e62e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vendor', sa.String(length=16), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('pci_slot', sa.String(length=32), nullable=True),
    sa.Column('usage_percent', sa.Float(), nullable=True),
    sa.Column('engine_gfx_percent', sa.Float(), nullable=True),
    sa.Column('engine_compute_percent', sa.Float(), nullable=True),
    sa.Column('engine_decode_percent', sa.Float(), nullable=True),
    sa.Column('engine_encode_percent', sa.Float(), nullable=True),
    sa.Column('vram_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('vram_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('core_clock_mhz', sa.Float(), nullable=True),
    sa.Column('memory_clock_mhz', sa.Float(), nullable=True),
    sa.Column('temperature_edge_celsius', sa.Float(), nullable=True),
    sa.Column('temperature_junction_celsius', sa.Float(), nullable=True),
    sa.Column('temperature_memory_celsius', sa.Float(), nullable=True),
    sa.Column('fan_rpm', sa.Integer(), nullable=True),
    sa.Column('power_watts', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_samples_id'), 'gpu_samples', ['id'], unique=False)
    op.create_index(op.f('ix_gpu_samples_timestamp'), 'gpu_samples', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    # Seed monitoring_config row for GPU (idempotent — only insert if missing).
    # NOTE: SQLAlchemy's SQLEnum stores by enum NAME, not value, so we use "GPU"
    # (uppercase) to match how MonitoringConfig(metric_type=MetricType.GPU) serializes.
    conn = op.get_bind()

    # On PostgreSQL the metrictype enum type pre-exists from earlier migrations
    # and does not yet contain 'GPU'. ALTER TYPE ... ADD VALUE must run outside
    # a transaction block, so commit first and use AUTOCOMMIT for the DDL.
    if conn.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            conn.execute(sa.text("ALTER TYPE metrictype ADD VALUE IF NOT EXISTS 'GPU'"))

    existing = conn.execute(
        sa.text("SELECT 1 FROM monitoring_config WHERE metric_type = :mt"),
        {"mt": "GPU"},
    ).scalar()
    if not existing:
        conn.execute(
            sa.text(
                "INSERT INTO monitoring_config "
                "(metric_type, retention_hours, db_persist_interval, is_enabled, samples_cleaned) "
                "VALUES (:mt, :rh, :pi, :en, :sc)"
            ),
            {"mt": "GPU", "rh": 168, "pi": 12, "en": True, "sc": 0},
        )


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM monitoring_config WHERE metric_type = :mt"), {"mt": "GPU"})
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_samples_timestamp'), table_name='gpu_samples')
    op.drop_index(op.f('ix_gpu_samples_id'), table_name='gpu_samples')
    op.drop_table('gpu_samples')
    # ### end Alembic commands ###
