"""Add backup table

Revision ID: fc75e3fa9c96
Revises: 152e33e84ff7
Create Date: 2025-11-24 18:51:55.293814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc75e3fa9c96'
down_revision: Union[str, Sequence[str], None] = '152e33e84ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('backup_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('includes_database', sa.Boolean(), nullable=False),
    sa.Column('includes_files', sa.Boolean(), nullable=False),
    sa.Column('includes_config', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index('idx_backup_creator_created', 'backups', ['creator_id', 'created_at'], unique=False)
    op.create_index('idx_backup_status_created', 'backups', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_backups_created_at'), 'backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_backups_creator_id'), 'backups', ['creator_id'], unique=False)
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_creator_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_created_at'), table_name='backups')
    op.drop_index('idx_backup_status_created', table_name='backups')
    op.drop_index('idx_backup_creator_created', table_name='backups')
    op.drop_table('backups')
    # ### end Alembic commands ###
